from .protocol import Paper
from datetime import datetime


SITE_URL = "https://helemnmmm.github.io/zotero-arxiv-daily"

framework = """
<!DOCTYPE HTML>
<html>
<head>
  <style>
    body {{ font-family: "EB Garamond", Georgia, serif; background: #fdfaf5; color: #1a1a1a; }}
    .container {{ max-width: 600px; margin: 0 auto; padding: 24px; }}
    h2 {{ font-family: "Playfair Display", Georgia, serif; color: #8b1a1a; border-bottom: 1.5px solid #8b1a1a; padding-bottom: 6px; }}
    .paper {{ border-bottom: 1px solid #e0d8cc; padding: 12px 0; }}
    .paper:last-child {{ border-bottom: none; }}
    .title {{ font-weight: 500; color: #8b1a1a; text-decoration: none; }}
    .meta {{ font-size: 0.9rem; color: #666; margin: 4px 0; }}
    .tldr {{ color: #333; margin: 6px 0; line-height: 1.6; }}
    .score {{ background: #8b1a1a; color: white; padding: 2px 8px; border-radius: 3px; font-size: 0.85rem; }}
    .btn {{ display: inline-block; background: #8b1a1a; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px; font-weight: 500; margin-top: 12px; }}
    .btn:hover {{ background: #5c0f0f; }}
    .footer {{ margin-top: 24px; font-size: 0.8rem; color: #999; border-top: 1px solid #d5cdbc; padding-top: 12px; }}
  </style>
</head>
<body>
<div class="container">

<h2>arXiv Daily · {date}</h2>

<p>今天共推荐 <strong>{total}</strong> 篇论文，已全部更新到网站上。</p>

<p><a href="{site_url}/daily/{date_slug}/" class="btn">浏览全部论文 →</a></p>

<h3 style="margin-top:24px;">今日亮点（Top {top_n}）</h3>

{top_papers}

<div class="footer">
  Generated by <a href="https://github.com/helemnmmm/zotero-arxiv-daily">zotero-arxiv-daily</a>. To unsubscribe, remove your email in your GitHub Action setting.
</div>

</div>
</body>
</html>
"""

top_paper_template = """
<div class="paper">
  <a href="{url}" class="title">{title}</a>
  <div class="meta">
    {authors} · <span class="score">★ {score}</span>
  </div>
  <div class="tldr">{tldr}</div>
</div>
"""


def render_email(papers: list[Paper]) -> str:
    today = datetime.now()
    date_str = today.strftime("%Y-%m-%d")

    if len(papers) == 0:
        return f"""<!DOCTYPE HTML><html><head></head><body style="font-family:Georgia,serif;background:#fdfaf5;text-align:center;padding:48px;">
        <h2>arXiv Daily · {date_str}</h2><p>今天没有新论文。休息一下！</p></body></html>"""

    top_n = min(5, len(papers))
    top_papers_html = ""
    for p in papers[:top_n]:
        authors = ", ".join(p.authors[:3])
        if len(p.authors) > 3:
            authors += " et al."
        score = f"{p.score:.1f}" if p.score else "—"
        top_papers_html += top_paper_template.format(
            url=p.url,
            title=p.title,
            authors=authors,
            score=score,
            tldr=p.tldr or p.abstract[:200],
        )

    return framework.format(
        date=date_str,
        date_slug=date_str,
        total=len(papers),
        top_n=top_n,
        top_papers=top_papers_html,
        site_url=SITE_URL,
    )
